#! /bin/csh -f

setenv n_nights `awk '($1=="N_NIGHTS"){print $2}' vaccine.param`

set cntr = 1
while ($cntr <= $n_nights)
cat ../raw_data/sky_n$cntr.list | awk '{print "./mkskyframe2 "$1,$2,$3,$4,$5,$6,$7}' > grun99
chmod 777 grun99
./grun99
rm -f grun99
@ cntr = $cntr + 1
end
